src/celen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("favicon.ico", include("django.contrib.staticfiles.urls")),
    path('', include('page.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ressource/', include('ressource.urls')),
    path("workload/", include("workload.urls"))
)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.index, name='accueil'),
]

src/ressource/urls.py
from django.urls import path
from ressource.views.utility import index
from ressource.views.users import *

app_name = 'ressource'

urlpatterns = [
    path('', index, name='accueil'),
	# PROFIL #
	path("profil/", profile, name="profile"),
    # USERS #
    path('user/add/', UserCreateView.as_view(), name="new-user"),
    path('user/<int:pk>/', UserDetailsView.as_view(), name="user-details"),
    path('users/', UsersList.as_view(), name="users-list"),
    path("users/import/", import_utilisateurs, name="users-import"),
    # PROBLEME REPORT #
    path('signaler-un-bug/', signaler_bug, name='signaler_bug')

]

src/workload/urls.py
from django.urls import path
from workload.views import index
from workload.crud.mission import *
from workload.crud.document import *
from workload.crud.projet import *
from workload.crud.commentaire import *
from workload.crud.tache import *
from workload.crud.livrable import *
from workload.crud.implication import *

app_name = 'workload'

urlpatterns = [
    path('', index, name='accueil'),
    # IMPLICATIONS #
    path("implications/", ImplicationListView.as_view(), name="implication_list"),
    path("implication/ajouter/<int:content_type_id>/<int:object_id>/", ImplicationCreateView.as_view(), name="implication_create"),
    path("implication/<int:pk>/modifier/", ImplicationUpdateView.as_view(), name="implication_edit"),
    path("implication/<int:pk>/supprimer/", ImplicationDeleteView.as_view(), name="implication_delete"),
    # LIVRABLES #
    path("livrables/", LivrableListView.as_view(), name="livrable_list"),
    path("livrables/nouveau/", LivrableCreateView.as_view(), name="livrable_create"),
    path("livrables/<int:pk>/", LivrableDetailView.as_view(), name="livrable_details"),
    path("livrables/<int:pk>/modifier/", LivrableUpdateView.as_view(), name="livrable_update"),
    path("livrables/<int:pk>/supprimer/", LivrableDeleteView.as_view(), name="livrable_delete"),
    # TACHES #
    path("taches/", TacheListView.as_view(), name="tache_list"),
    path("taches/create/", TacheCreateView.as_view(), name="tache_create"),
    path("taches/<int:pk>/", TacheDetailView.as_view(), name="tache_details"),
    path("taches/<int:pk>/edit/", TacheUpdateView.as_view(), name="tache_update"),
    path("taches/<int:pk>/delete/", TacheDeleteView.as_view(), name="tache_delete"),    
    # COMMENTAIRES #
    path("commentaires/", CommentaireListView.as_view(), name="commentaire_list"),
    path("commentaire/ajouter/<int:content_type_id>/<int:object_id>/", CommentaireCreateView.as_view(), name="commentaire_create"),
    path("commentaire/<int:pk>/modifier/", CommentaireUpdateView.as_view(), name="commentaire_update"),
    path("commentaire/<int:pk>/supprimer/", CommentaireDeleteView.as_view(), name="commentaire_delete"),
    path("commentaire/<int:pk>/details/", CommentaireDetailView.as_view(), name="commentaire_details"),
    # PROJETS #
    path("projets/", ProjetListView.as_view(), name="projet_list"),
    path("projet/<int:pk>/", ProjetDetailView.as_view(), name="projet_details"),
    path("projet/ajouter/", ProjetCreateView.as_view(), name="projet_create"),
    path("projet/<int:pk>/modifier/", ProjetUpdateView.as_view(), name="projet_update"),
    path("projet/<int:pk>/supprimer/", ProjetDeleteView.as_view(), name="projet_delete"),
    # DOCUMENTS #
    path("documents/", DocumentListView.as_view(), name="documents_list"),
    path('document/ajouter/<int:content_type_id>/<int:object_id>/', document_create, name='document_create'),
    path('document/<int:pk>/modifier/', document_update, name='document_update'),
    path('document/<int:pk>/effacer/', DocumentDeleteView.as_view(), name='document_delete'),
    # MISSIONS #
    path("missions/", MissionListView.as_view(), name="missions_list"),
    path("mission/<int:pk>/details/", MissionDetailView.as_view(), name="mission_details"),
    path("mission/<int:pk>/effacer/", MissionDeleteView.as_view(), name="mission_delete"),
    path("mission/creation/", MissionCreateView.as_view(), name="mission_create"),
    path("mission/<int:pk>/modifier/", MissionUpdateView.as_view(), name="mission_update"),
]

src/workload/forms.py
from django import forms
from workload.models import Implication, Document, Commentaire, Projet, Tache, Livrable
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class ImplicationForm(forms.ModelForm):
    class Meta:
        model = Implication
        fields = [
            "agent",
            "nature",
            "contribution",
            "role",
            "start_date_prevue",
            "end_date_prevue",
            "start_date_reel",
            "end_date_reel",
        ]
        widgets = {
            "start_date_prevue": forms.DateInput(attrs={"type": "date"}),
            "end_date_prevue": forms.DateInput(attrs={"type": "date"}),
            "start_date_reel": forms.DateInput(attrs={"type": "date"}),
            "end_date_reel": forms.DateInput(attrs={"type": "date"}),
            "contribution": forms.NumberInput(attrs={
                "type": "range", 
                "min": 0, 
                "max": 100, 
                "class": "form-range"}),

        }

    def clean(self):
        cleaned_data = super().clean()
        agent = cleaned_data.get("agent")

        if not self.instance.pk:  # seulement à la création
            content_type = self.initial.get("content_type")
            object_id = self.initial.get("object_id")

            # vérification de la contrainte d’unicité
            if Implication.objects.filter(
                content_type_id=content_type,
                object_id=object_id,
                agent=agent
            ).exists():
                raise ValidationError("Cet agent est déjà impliqué dans cet objet.")

        return cleaned_data

class CommentaireForm(forms.ModelForm):
    class Meta:
        model = Commentaire
        fields = ["type", "contenu"]

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['nom', 'url']
        widgets = {
            'nom': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Si vide, sera remplacé par l'identifiant de l'url"
            }),
            'url': forms.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Lien complet vers la GED',
                'required': True
            }),
        }

class ProjetForm(forms.ModelForm):
    class Meta:
        model = Projet
        exclude = ("documents", "commentaires","implications")
        widgets = {
            "start_date_prevue": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "end_date_prevue": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "start_date_reel": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "end_date_reel": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "percent_complete": forms.NumberInput(attrs={
                "type": "range", 
                "min": 0, 
                "max": 100, 
                "class": "form-range"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Sans ça, Django n’affiche pas la date existante
        for field in [
            "start_date_prevue",
            "end_date_prevue",
            "start_date_reel",
            "end_date_reel",
        ]:
            if self.instance and getattr(self.instance, field):
                # Force le format HTML5
                self.fields[field].initial = getattr(self.instance, field).strftime("%Y-%m-%d")
        
class TacheForm(forms.ModelForm):
    class Meta:
        model = Tache
        fields = [
            "nom",
            "description",
            "complete",
            "mission",
            "projet",
            "tags",
        ]

class LivrableForm(forms.ModelForm):
    class Meta:
        model = Livrable
        fields = "__all__"
        widgets = {
            "start_date_prevue": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "end_date_prevue": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "start_date_reel": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "end_date_reel": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Sans ça, Django n’affiche pas la date existante
        for field in [
            "start_date_prevue",
            "end_date_prevue",
            "start_date_reel",
            "end_date_reel",
        ]:
            if self.instance and getattr(self.instance, field):
                # Force le format HTML5
                self.fields[field].initial = getattr(self.instance, field).strftime("%Y-%m-%d")

src/workload/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from workload.models import *

def get_objects_grouped(user):
	data = {
		"missions": set(),
		"projets": set(),
		"livrables": set(),
		"taches": set(),
	}
	# 1. via Implication
	for imp in Implication.objects.filter(agent=user):
		obj = imp.cible
		if isinstance(obj, Mission):
			data["missions"].add(obj)
		elif isinstance(obj, Projet):
			data["projets"].add(obj)
		elif isinstance(obj, Livrable):
			data["livrables"].add(obj)
		elif isinstance(obj, Tache):
			data["taches"].add(obj)
			
	# 2. via responsabilités directes (Projets, Livrables)
	data["projets"].update(Projet.objects.filter(r1=user))
	data["projets"].update(Projet.objects.filter(r2=user))
	data["livrables"].update(Livrable.objects.filter(responsable=user))

	return {k: list(v) for k, v in data.items()}

@login_required
def index(request):
	return render(request, "workload/accueil.html")

src/workload/views/livrable.py
from workload.models import *
from workload.forms import LivrableForm
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView

class LivrableListView(LoginRequiredMixin, ListView):
    model = Livrable
    template_name = "workload/livrable/livrable_list.html"
    context_object_name = "livrables"

class LivrableCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Livrable
    form_class = LivrableForm
    template_name = "workload/livrable/livrable_create.html"
    success_message = "Livrable créé avec succès"

class LivrableUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Livrable
    form_class = LivrableForm
    template_name = "workload/livrable/livrable_create.html"
    success_message = "Livrable mis à jour avec succès"


class LivrableDetailView(LoginRequiredMixin, DetailView):
    model = Livrable
    template_name = "workload/livrable/livrable_details.html"

class LivrableDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Livrable
    template_name = "warning/objet_a_effacer.html"
    success_message = "Livrable supprimé avec succès"

    def get_success_url(self):
        # si next= est fourni dans l’URL, on le suit
        next_url = self.request.GET.get("next") or self.request.POST.get("next")
        if next_url:
            return next_url
        return reverse("workload:livrable_details", kwargs={"pk": self.pk})

src/workload/templates/workload/mission/mission_create.html
{% extends 'public/base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block titre %}{% if '/modifier/' in request.path %}Modifier la {% else %}Nouvelle {% endif %}Mission{% endblock %}

{% block css_supp %}
{% endblock %}

{% block contenu %}
<div class="container min-vh-100 col-md-6 mx-auto">
    <div class="row mb-3">
        <div class="col">
            <h3>{% if '/modifier/' in request.path %}Modifier la {% else %}Nouvelle {% endif %}Mission</h3>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body py-2">
                    <div class="d-grid gap-2 d-md-block text-center">
                        <button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-save me-2"></i>Créer</button>
                        <button class="btn btn-secondary btn-sm" onclick="history.back();"><i class="bi bi-arrow-left-circle me-2"></i>Annuler</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
{% endblock %}

{% block js_supp %}
{% endblock %}

src/workload/templates/workload/mission/mission_details.html
{% extends 'public/base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block titre %}Mission {{ object }}{% endblock %}

{% block css_supp %}
<style>
.avatar {
    display: inline-block;
    vertical-align: middle;
    width: 26px;
    height: 26px;
    border-radius: 50%;
}
.avatars {
    display: flex;
    gap: 2px; /* ou 0 si tu veux collés */
    align-items: center;
}
</style>
{% endblock %}

{% block contenu %}
<div class="container">
    <div class="row mb-3 align-items-center">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <h2>Mission : {{ object }}</h2>
                    <span class="small fst-italic">Créée {{ object.created|naturaltime }} par {{ object.created_by }} 
                        {% if object.modified_by %}
                        et modifiée {{ object.modified|naturaltime }} par {{ object.modified_by }}
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-3 g-3" data-masonry='{"percentPosition": true }'>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <h3>Description</h3>
                    <ul class="list-inline small mb-3">
                        <li class="list-inline-item">
                            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.400rem, 0);" href="{% url 'workload:mission_update' object.pk %}?next={{ request.path }}">
                            <i class="bi bi-pencil-square"></i>
                            Editer
                            </a>
                        </li>
                    </ul>
                    <p>{{ object.description }}</p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <h3>Projets</h3>
                    <ul class="list-inline small mb-3">
                        <li class="list-inline-item">
                            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.400rem, 0);" href="{% url 'workload:projet_create' %}?next={{ request.path }}">
                            <i class="bi bi-plus-circle"></i>
                            Ajouter
                            </a>
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        {% for projet in object.projets.all %}
                        <li class="py-1">
                            <a href="{% url 'workload:projet_details' projet.pk %}" class="text-decoration-none">
                                {{ projet }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <h3>{{ object.documents.all|length }} Documents</h3>
                    <ul class="list-inline small mb-3">
                        <li class="list-inline-item">
                            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.400rem, 0);" href="{% url 'workload:document_create' object.get_content_type_id object.pk %}?next={{ request.path }}">
                            <i class="bi bi-plus-circle"></i>
                            Ajouter
                            </a>
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        {% for doc in object.documents.all %}
                        <li class="d-flex justify-content-between">
                            <a target="_blank" href="{{ doc.url }}" class="small">{{ doc.nom|slice:"25" }}...</a>
                            <ul class="list-unstyled">
                                <li class="list-inline-item">
                                    <a href="{% url 'workload:document_update' pk=doc.pk %}?next={{ request.path }}"><i class="bi bi-pencil-square text-warning"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="{% url 'workload:document_delete' pk=doc.pk %}?next={{ request.path }}"><i class="bi bi-trash3 text-danger"></i></a>
                                </li>
                            </ul>
                            
                        </li>
                        {% endfor %}
                    </ul>                    
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <h3>{{ object.commentaires.all|length }} Commentaire{% if object.commentaires.all|length > 1 %}s{% endif %}</h3>
                    <ul class="list-inline small mb-3">
                        <li class="list-inline-item">
                            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.400rem, 0);" href="{% url 'workload:commentaire_create' object.get_content_type_id object.pk %}?next={{ request.path }}">
                            <i class="bi bi-plus-circle"></i>
                            Ajouter
                            </a>
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        {% for com in object.commentaires.all %}
                        <li class="d-flex justify-content-between">
                            <a href="{% url 'workload:commentaire_details' com.pk %}" class="small">
                                {{ com.get_type_display }} {{ com.created|naturaltime }}
                            </a>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <a href="{% url 'workload:commentaire_update' pk=com.pk %}?next={{ request.path }}"><i class="bi bi-pencil-square text-warning"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="{% url 'workload:commentaire_delete' pk=com.pk %}?next={{ request.path }}"><i class="bi bi-trash3 text-danger"></i></a>
                                </li>
                            </ul>                            
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body py-2">
                    <div class="d-grid gap-2 d-md-block text-center">
                        <a class="btn btn-sm btn-secondary" role="button" href="{% url 'ressource:profile' %}"><i class="bi bi-arrow-left-circle me-1"></i>Retour</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_supp %}
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
{% endblock %}

src/workload/templates/workload/mission/missions_list.html
{% extends 'public/base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load utility %}

{% block titre %}Missions{% endblock %}

{% block css_supp %}
<link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css">
{% endblock %}

{% block contenu %}
<div class="container min-vh-100">
    <div class="row mb-3 align-items-center">
        <div class="col">
            <h1>Missions</h1>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body">
                    <table id="table_id" class="display" width="100%">
                        <thead>
                            <tr>
                                <th>Mission</th>
                                <th>Description</th>
                                <th>Date</th>
                                <th>Projets</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for m in object_list %}
                            <tr class="align-items-center">
                                <td><a href="{% url 'workload:mission_details' m.pk %}">{{ m.nom }}</a></td>
                                <td>{{ m.description|slice:"75" }}...</td>
                                <td>{{ m.created|naturaltime }}</td>
                                <td>{{ m.projets.all|length }}</td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item" data-bs-toggle="tooltip" data-bs-title="Ajouter un commentaire">
                                            <a href="{% url 'workload:commentaire_create' m.get_content_type_id m.pk %}?next={{ request.path }}"><i class="bi bi-chat-dots text-warning"></i></a>
                                        </li>
                                        <li class="list-inline-item" data-bs-toggle="tooltip" data-bs-title="Ajouter un document">
                                            <a href="{% url 'workload:document_create' m.get_content_type_id m.pk %}?next={{ request.path }}"><i class="bi bi-file-plus text-primary"></i></a>
                                        </li>
                                        <li class="list-inline-item" data-bs-toggle="tooltip" data-bs-title="Editer la mission">
                                            <a href="{% url 'workload:mission_update' m.pk %}"><i class="bi bi-pencil-square text-success"></i></a>
                                        </li>
                                        <li class="list-inline-item" data-bs-toggle="tooltip" data-bs-title="Supprimer la mission">
                                            <a href="{% url 'workload:mission_delete' m.pk %}?next={{ request.path }}"><i class="bi bi-trash3 text-danger"></i></a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>        
    </div>
    <div class="row mb-3">
        <div class="col">
            <div class="card shadow-lg bg-body">
                <div class="card-body py-2">
                    <div class="d-grid gap-2 d-md-block text-center">
                        <a class="btn btn-sm btn-primary" role="button" href="{% url 'workload:mission_create' %}?next={{ request.path }}"><i class="bi bi-plus-circle me-1"></i>Ajouter une Mission</a>
                        <a class="btn btn-sm btn-secondary" role="button" href="{% url 'ressource:profile' %}"><i class="bi bi-arrow-left-circle me-1"></i>Retour</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_supp %}
<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script type="text/javascript">
	$(document).ready( function () {
    $('#table_id').DataTable({
    responsive: true
});
} );
</script>

{% endblock %}